### ISSUE TITLE
Migration to V4 protocol version fail

### ISSUE THREAD

**Issue by lleleux** [complexdatacollective/Architect#689] opened 2020-12-24 00:01 UTC
Hi,

When I try to migrate from v3 to v4, I have this error :
![Screenshot from 2020-12-24 00-50-16](https://user-images.githubusercontent.com/6029811/103045022-2775dc80-4583-11eb-9fb6-170b69790be7.png)
I'm on Ubuntu 20.10, and my /home is on another partition than /tmp.

I asked to write the new version to /tmp, and it worked. But I have the same problem when I copy the protocol to my /home, update it, and try to save it.

As a workaround, I work on another partition for the moment.

Thank you for your work.

Laurent

**Comment by lleleux** [comment] 2020-12-24 00:10
If I'm not wrong, you are using the "rename" function to move the file from /tmp to the new location. But I think it doesn't work cross partitions. You need maybe to copy and then unlink the file.

If this can help you ;-)

**Comment by jthrilly** [comment] 2021-01-04 10:21
Thanks @lleleux! You're almost certainly right about the root cause. We had a bit of an internal discussion about "renaming" vs "moving" (where moving is first copying and then unlinking). It seems there is in fact a difference between the two. 

Thank you for catching this. A fix will be coming as soon as we are all back in the office.

**Comment by wwqrd** [comment] 2021-01-11 10:21
This might also explain some of the issues with the snap packages (which are sand-boxed with their own `/tmp/` dir), since protocols are created in the temp dir before being renamed to user space.

**Comment by wwqrd** [comment] 2021-01-20 11:09
Should be resolved by https://github.com/complexdatacollective/Architect/pull/691 which changes the `rename` method to `copy`

**Closed** 2021-02-12 12:43 UTC
Labels: bug
